//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1434
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wzd.DirectUI.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wzd.DirectUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderBottom {
            get {
                object obj = ResourceManager.GetObject("IMBorderBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderBottom2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderBottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderLeft {
            get {
                object obj = ResourceManager.GetObject("IMBorderLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderLeft2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderLeft2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderLeftBottom2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderLeftBottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderLeftTop2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderLeftTop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderRight {
            get {
                object obj = ResourceManager.GetObject("IMBorderRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderRight2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderRight2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderRightBottom2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderRightBottom2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderRightTop2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderRightTop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderTop {
            get {
                object obj = ResourceManager.GetObject("IMBorderTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderTop2 {
            get {
                object obj = ResourceManager.GetObject("IMBorderTop2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMBorderTop20 {
            get {
                object obj = ResourceManager.GetObject("IMBorderTop20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMCloseButton_Down {
            get {
                object obj = ResourceManager.GetObject("IMCloseButton_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMCloseButton_Hover {
            get {
                object obj = ResourceManager.GetObject("IMCloseButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMCloseButton_Normal {
            get {
                object obj = ResourceManager.GetObject("IMCloseButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMaxButton_Down {
            get {
                object obj = ResourceManager.GetObject("IMMaxButton_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMaxButton_Hover {
            get {
                object obj = ResourceManager.GetObject("IMMaxButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMaxButton_Normal {
            get {
                object obj = ResourceManager.GetObject("IMMaxButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMinButton_Down {
            get {
                object obj = ResourceManager.GetObject("IMMinButton_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMinButton_Hover {
            get {
                object obj = ResourceManager.GetObject("IMMinButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMMinButton_Normal {
            get {
                object obj = ResourceManager.GetObject("IMMinButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMRestoreButton_Down {
            get {
                object obj = ResourceManager.GetObject("IMRestoreButton_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMRestoreButton_Hover {
            get {
                object obj = ResourceManager.GetObject("IMRestoreButton_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IMRestoreButton_Normal {
            get {
                object obj = ResourceManager.GetObject("IMRestoreButton_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
